### ISSUE TITLE
ossfs使用的疑问

### ISSUE THREAD

**Issue by zxkane** [alibaba/ossfs#2]
我在使用**ossfs**过程中，遇到一些错误。但是项目中并没有相关Usage文档，我不知道是否是由于不正确使用导致的错误。下面是我的环境和使用方法，还请帮忙指出如何正确使用ossfs。谢谢。

Env:

Aliyun ECS Ubuntu 14.04.3 LTS

我通过以下命令mount existing OSS bucket

``` shell
sudo ./ossfs -i the-id -k the-key --host oss-cn-beijing-internal.aliyuncs.com -b my-bucket -d  /mnt/oss
```

执行ossfs命令后，发现ossfs并没有在后台运行，而是运行在前台。如果加上`&`把ossfs放在后台运行，但发现mountpoint `/mnt/oss`没有被mount上。

当ossfs在前台执行的时候，得到以下默认输出，

``` shell
could not find ParserDetails.ini in /usr/local/share/perl/5.18.2/XML/SAX
Use of uninitialized value in subroutine entry at /usr/local/lib/perl/5.18.2/Fuse.pm line 147.
FUSE library version: 2.9.2
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.22
flags=0x0000f7fb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
```

但当我执行`ls /mnt/oss`的时候，得到类似下面的错误，

``` shell
LOOKUP /a2cd8518-4079-415d-b18f-83665f6553b4
getattr /a2cd8518-4079-415d-b18f-83665f6553b4
   unique: 104, error: -2 (No such file or directory), outsize: 16
unique: 105, opcode: LOOKUP (1), nodeid: 1, insize: 77, pid: 8012
LOOKUP /a3f92c99-7c89-43e9-930d-107fa4b78f43
getattr /a3f92c99-7c89-43e9-930d-107fa4b78f43
   unique: 105, error: -2 (No such file or directory), outsize: 16
unique: 106, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 8012
   unique: 106, success, outsize: 16
unique: 107, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
releasedir[0] flags: 0x0
   unique: 107, success, outsize: 16
```

**ls**能够列出bucket下面的文件夹，但无法访问这些文件夹。

``` shell
?????????? ? ? ? ?            ? a1afac2b-cb85-4aab-8570-aac364c8fe49
?????????? ? ? ? ?            ? a25c7d24-a64e-413e-a913-39f3416999fa
?????????? ? ? ? ?            ? a26cf59a-d745-4c71-97c3-2dc18624f947
```

**Comment by lyman** [comment]
看起来应该是环境的问题 http://www.perlmonks.org/?node_id=431053

ubuntu 应该也可以装个什么包就解问题，但是我不熟悉 ubuntu 环境。

**Comment by lyman** [comment]
另，-d 是 debug 模式，这个模式是在前台的。不加 -d 自然会在后台。

**Comment by zxkane** [comment]
@lyman 谢谢你的分析。

根据你推荐的链接，下面的WARN/ERROR中的第一个被解决了。

~~could not find ParserDetails.ini in /usr/local/share/perl/5.18.2/XML/SAX~~
**Use of uninitialized value in subroutine entry at /usr/local/lib/perl/5.18.2/Fuse.pm line 147.**

``` pm
142                 } else {
143                         carp("Thread support was not compiled into this build of perl.\nThreads are disabled.\n");
144                         $otherargs{threaded} = 0;
145                 }
146         }
147         perl_fuse_main(@otherargs{@otherargs},@subs);
148 }
149 
150 sub fuse_buf_size {
151         my ($buf) = @_;
152         return sum(map { $_->{size} } @$buf);  
153 }  
154 
155 # Autoload methods go after =cut, and are processed by the autosplit program.
```

但是第二个错误还是google不到方案。

Perl对我来说之前也没接触过，问题追查起来很棘手。是否可以建议下，**ossfs**在哪些[Aliyun ECS支持的Linux发行版](https://ecs-buy.aliyun.com/#/prepay)中测试过，并且能够运行的？Gentoo, Centoo or Aliyun Linux?

谢谢。

**Comment by lyman** [comment]
第二个是个 warning，看起来应该是 perl-fuse 的版本的问题。

ossfs 是我个人业余时间的作品，没有在 aliyun ecs 上测试过，我的开发环境是 ArchLinux，之前是没问题的。

我刚刚跑了下测试，case 全都 fail 了，估计是 server 端又做过什么改动，ossfs 没有配套跟进。这个我稍后会查一下。

**Comment by zxkane** [comment]
@lyman 谢谢！！

我看这个项目在**Alibaba**这个组织下，按常理应该是官方支持的项目。

**Comment by lyman** [comment]
测试失败是因为我之前的 access id key 失效了。

目前代码的状态是绝大多数 api 能用。

依葫芦画瓢，`perl -MCPAN -e 'install Fuse'` 这样试试看？

**Comment by zxkane** [comment]
@lyman 我试过了。在ECS的Ubuntu 14.04上还是不行。

**Comment by lyman** [comment]
代码我测过没问题了。应该就是 ECS 的环境问题。回头我搞个 ECS 试试看吧。

**Comment by zxkane** [comment]
谢谢。
由于项目需要用到这个feature，我写了个[Java版本](https://github.com/videome/AliyunOSSFS)的自用。欢迎点评。

**Comment by lyman** [comment]
赞美自力更生。虽然可能用不上了，但还是在这里结个案。

今天用 aliyun ecs ubuntu 14.04 试了一下，安装以下包之后，是可以正常工作的，所有的测试用例都可以过。

```
   35  sudo apt-get install libhttp-date-perl
   37  sudo apt-get install libfuse-perl
   42  sudo apt-get install libxml-simple-perl
   45  sudo apt-get install libdigest-hmac-perl
```

最好的结果应该是打个 ossfs 的 deb 到源里。不过小众软件如果没有志愿者愿意维护打包确实是个麻烦事。

**Comment by hongtao12310** [comment]
我已经成功的在本地虚拟机(virtualbox + ubuntu14.04)上面运行ossfs. 非常感谢lyman的大力support ！
